export const GET_BLOCKCHAIN = 'GET_BLOCKCHAIN';
export const GET_BLOCKCHAIN_SUCCESS = 'GET_BLOCKCHAIN_SUCCESS';
export const GET_BLOCKCHAIN_ERROR = 'GET_BLOCKCHAIN_ERROR';

export const CONNECT_WALLET = 'CONNECT_WALLET';
export const CONNECT_WALLET_SUCCESS = 'CONNECT_WALLET_SUCCESS';
export const CONNECT_WALLET_ERROR = 'CONNECT_WALLET_ERROR';

export const CONNECT_MIGRATE = 'CONNECT_MIGRATE';
export const CONNECT_MIGRATE_SUCCESS = 'CONNECT_MIGRATE_SUCCESS';
export const CONNECT_MIGRATE_ERROR = 'CONNECT_MIGRATE_ERROR';